### ISSUE TITLE
Where do you put 2 and 6 for the PS/2?

### ISSUE THREAD

**Issue by Clodmachine** [trekawek/mac-plus-ps2#2]
pin 2 and 6 for the ps2 pinout aren't there

**Comment by trekawek** [comment]
These pins are unused. They don't need to be connected to anything.

**Comment by trekawek** [comment]
Also, I updated the README.md in ccb9be80b8ae99e5a44bc14f562e2c6dcd3a71d6, so it should be more clear now.

**Comment by Clodmachine** [comment]
Great! One more question though. Which audrino is it? I'm hoping to make
this and I can't really tell which one it is.

**Comment by trekawek** [comment]
I think it should work with any Arduino. I created a prototype on Arduino Uno and then the working device on Arduino Uno Nano (to make it more compact).

**Comment by Clodmachine** [comment]
Ok, because I saw [this](https://www.ebay.com/itm/MINI-USB-Nano-V3-0-ATmega328P-CH340G-5V-16M-Micro-controller-board-for-Arduino/401592119121) looked like the one in the pic.
